name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: yarn install

      - name: Run Cypress Tests
        run: yarn cy

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos

      - name: Check Test Results
        run: |
          # Assuming your Cypress output folder contains a 'results' directory
          if [[ -d cypress/results ]]; then
            failed_tests=$(grep -rl "failed" cypress/results)
            if [[ -n "$failed_tests" ]]; then
              echo "Tests failed. Marking the pull request as failed."
              exit 1
            fi
          fi
